### ISSUE TITLE
Get NullPointerException if Global secondary index didn't contains column *amzn-ddb-map-desc* and *amzn-ddb-map-sig*

### ISSUE THREAD

**Issue by gdwneo** [awslabs/aws-dynamodb-encryption-java#20] opened 2016-07-28 10:27 UTC
In each of the encrypted table, will contains two column *amzn-ddb-map-desc* and *amzn-ddb-map-sig*, they are use for data decryption, but in my global secondary index I didn't put any encrypt column inside so by right these two column should not be required, so is there any way to ignore these two fields when it is not available?
![1](https://cloud.githubusercontent.com/assets/1762137/17209670/dd388c30-54f0-11e6-8601-1563e98bd025.png)

**Comment by SalusaSecondus** [comment] 2016-07-28 16:06
Currently, the library requires all fields in order to parse the record. If you do not require either decryption or integrity checks, then just examine the results from Dynamo directly and don't bother passing them through the library. If you need integrity checks, then you'll need to include everything in your secondary index.

There is a long-term desire to support decryption and verification for subsets of the records, but we haven't had the time to build this yet (and it results in significantly larger signatures)

(Closing because this is working as designed.)

**Closed by SalusaSecondus** 2016-07-28 16:06 UTC
